"""Classroom model. TODO: implement."""

# class Classroom(db.Model):
#     __tablename__ = "classrooms"
#     id = ...
#     name = ...
#     bench_count = ...
#     students_per_bench = ...  # 1, 2, or 3
