"""Bench model with numbering. TODO: implement."""

# class Bench(db.Model):
#     __tablename__ = "benches"
#     id = ...
#     classroom_id = ...
#     bench_number = ...
#     row = ...
#     col = ...
