"""Student model (from CSV: ID, Name, Skill, Classroom). TODO: implement."""

# class Student(db.Model):
#     __tablename__ = "students"
#     id = ...
#     student_id = ...       # external Student ID from CSV
#     name = ...
#     skill = ...
#     classroom_id = ...
#     bench_id = ...         # assigned after seating logic
#     seat_position = ...    # position on bench (1/2/3)
